### ISSUE TITLE
QuadTree Definition

### ISSUE THREAD

**Issue by JerryLife** [spatialdatasciencegroup/HST#2]
I am working on a related study and really appreciate your releasing the source code.

After carefully examing the codes, I failed to understand how the quadtree is used in the training. There is one import in `train.py`, but those components in `quadtreev2` is never defined in this repo. Could the authors add more details about it? Thanks!

**Comment by ruid7181** [comment]
Hello, I have the same problem about this `quadtreev2`. Have you figured it out yet? Thanks a lot.

**Comment by JerryLife** [comment]
No, I haven't. Since I received no reply, I gave up referring to this study.

**Comment by wenchonghekk** [comment]
Hello, 
Thank you for your interest in our work. 
The quadtreev2 is used in the preprocessing step instead of the model training process. I will upload a more specific instruction on how to use the preprocessing code.

**Comment by JerryLife** [comment]
Thank you for your explanation! May I know if there is any update regarding the detailed instruction? Your help is greatly appreciated.
